apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promentum-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Moazzam06/Promentum-App-Config.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: promentum-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
