apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promentum-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Moazzam06/Promentum-App-Config.git
    targetRevision: main
    path: kubernetes/overlays/development
  destination: 
    server: https://d5b651e8-bf3c-4963-9522-546ed5c8c22a.k8s.ondigitalocean.com
    namespace: promentum-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
