apiVersion: v1
kind: Service
metadata:
  name: network-service
  labels:
    app: network
spec:
  selector:
    app: network
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    #nodePort: 32001  # NodePort for HTTP
    name: http
  type: ClusterIP